### ISSUE TITLE
カーネル法のノートの ToDo リスト

### ISSUE THREAD

**Issue by Yagami360** [Yagami360/My_NoteBook#7]
[18/11/05]
チェック付き＝完了済み

- [x] 概要の整理
- [x] ~~再生核ヒルベルト空間の記号を H から \scriptH へ変更~~
- [x] 正定値カーネル、負定値カーネルの定義の和の形の確認
- [x] ~~正定値カーネルの定義の解釈図を追加~~
- [x] 「ヒルベルト埋め込み写像による再生核ヒルベルト空間の構成」の項目を１つの定理としてまとめる
- [x] 「フーリエ変換と埋め込み写像」の項目を１つの定理としてまとめる
- [x] 正定値カーネルの項目の概要説明を追加（カーネルトリックとの関係を交えながら）
- [x] 再生核ヒルベルト空間の項目の概要説明を追加（特徴写像、特徴空間との関連を交えながら）
- [x] カーネル主成分分析の簡単な適用例を追加（次元削除による特徴抽出の例など）
- [x] サポートベクターマシンの簡単な適用例を追加（irisデータの種類の分類問題の例など）
